name: Build gl4es-114
on: [push, workflow_dispatch]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build GL4ES
        run: |
         # wget https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip
         # unzip android-ndk-r20b-linux-x86_64.zip >> /dev/null
         $ANDROID_NDK_HOME/ndk-build APP_BUILD_SCRIPT=./Android.mk NDK_PROJECT_PATH=.
         $ANDROID_NDK_HOME/ndk-build APP_BUILD_SCRIPT=./Android_debug.mk NDK_PROJECT_PATH=.
      - name: Upload GL4ES libs
        uses: actions/upload-artifact@v2
        with:
          name: gl4es-112-android
          path: libs/*
      - name: Upload GL4ES debug libs
        uses: actions/upload-artifact@v2
        with:
          name: gl4es-112-android
          path: 'obj/**/*.so'
